import type { Metadata } from "next";
import "./globals.css";
import './collors.css'
import { Providers } from "@/components/Providers";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Sidebar />
          <div className="wrapper">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
